#!/usr/bin/bash

#info
VERSION=1.0

#env and path
if [ -z "$ROOT" ]; then ROOT="/";fi
PATH=$ROOT/bin:$ROOT/usr/bin:$ROOT/usr/sbin:$ROOT/usr/local/bin:$ROOT/usr/local/sbin
PATH_PACKAGE=$ROOT/var/log/packages
SLACKWARE_VERSION=$(cat $ROOT/etc/slackware-version)
if [ -z "$LDD" ];then LDD=$ROOT/usr/bin/ldd;fi
WORKDIR=$ROOT/var/lib/slackpkg
PREPO=slackware

#time
NO_TIME=0
SECONDS=0
D=0
H=0
M=0
str_time_conting=""


PRIORITY=($(ls $WORKDIR/*-filelist.gz | xargs -n1 basename | sed 's/-filelist\.gz$//'))





help(){
	if [[ "$1" == "h" ]];then
		echo "slackldd [-v] [-t] package"
	elif [[ "$1" == "arg_error" ]];then
		echo "invalid argument: $2"
	elif [[ "$1" == "v" ]];then
		echo "slackldd version: $VERSION"
	else
		echo "error"
	fi
	exit
}


counting_time(){
	while [[ $SECONDS -ge 60 ]];do
		((m++))
		((SECONDS -= 60))
	done
	while [[ $m -ge 60 ]];do
		((h++))
		(($m -= 60))
	done
	while [[ $h -ge 24 ]];do
		((d++))
		((h -= 24))
	done
	str_time_conting="sec:$SECONDS"
	if [[ -n $m && $m -ge 1 ]];then
		str_time_conting="$str_time_conting min: $m"
	fi
	if [[ -n $h && $h -ge 1 ]];then
		str_time_conting="$str_time_conting hour: $h"
	fi
	if [[ -n $d && $d -ge 1 ]];then
		str_time_conting="$str_time_conting day: $d"
	fi
	echo "$str_time_conting"
}

cutpkg(){
    echo "$1" | sed -E 's/-[0-9].*//'
}

file_search(){
    local INPUTLIST="$1"
    local PKGNAMELIST=$(mktemp)
    local RESULT_LIST=""

    for i in "${PRIORITY[@]}"; do
        FILELIST="${WORKDIR}/${i}-filelist.gz"
        if [ -f "$FILELIST" ]; then
	    PKGS=$(zcat "$FILELIST" | grep "$INPUTLIST" | awk '{print $1}' | xargs -r -n1 basename)
            for FULLNAME in $PKGS ; do
                NAME=$(cutpkg "$FULLNAME")
                if ! grep -q "^${NAME}$" "$PKGNAMELIST"; then
					echo "$NAME" >> "$PKGNAMELIST"
					if [[ "$PACKAGE_ONLY" == "1" ]];then
						echo "$FULLNAME"
                    else
						echo -e "$FULLNAME in $i"
                    fi
                fi
            done
        fi
    done

    rm -f "$PKGNAMELIST"
}



ldd_check(){
	for st in "$@";do
		$LDD "$ROOT/$st" 2>/dev/null | awk '/not found/ {print $1}'
	done
}

check_exe() {
	if [[ -x "$ROOT/$1" ]] && [[ -f "$ROOT/$1" ]]; then
		return 0
	fi
	return 1
}
string_winding(){
	for st in "$@";do
		if check_exe "$st";then
			echo "$BINS $st"
		fi
	done
}

find_package(){
	not_found_package=()
	for st in ${main_arg[@]}; do
		FILE=("$PATH_PACKAGE"/*"$st"*)
		if [[ -f "${FILE[0]}" ]];then
			package+=("${FILE[0]}")
		else
			not_found_package+=("$st")
		fi
	done	
}


filter_arg(){
    local -A seen
    for i in "${!main_arg[@]}"; do
        local val="${main_arg[$i]}"
        if [[ -n "${seen[$val]}" ]]; then
            unset "main_arg[$i]" 
        else
            seen[$val]=1 
        fi
    done
    main_arg=("${main_arg[@]}") # Схлопываем массив обратно
}


filter_arg_str(){
	local tmp_main_arg="$@"
	local main_arg_return=()
	for st in $tmp_main_arg;do
		if [[ "$tmp_main_arg" == *"$st"* ]];then
			main_arg_return+=("$st")
		fi
	done
	echo "${main_arg_return[@]}"
}


not_found_package=()
package=()
main_arg=()
main(){
	shopt -s nullglob
	BINS=""
	BIN=""
	if [[ "$@" == "" ]];then
		help h
	fi
	
	for tmp_main_arg in "$@";do
		if [[ "$tmp_main_arg" == "-h" ]];then
			help h
		elif [[ "$tmp_main_arg" == "-v" ]];then
			help v
		elif [[ "$tmp_main_arg" == "-t" ]];then
			NO_TIME=1
		elif [[ "$tmp_main_arg" == "-p" ]];then
			PACKAGE_ONLY=1
			continue
		else
			if [[ "${tmp_main_arg::1}" == "-" ]];then
				help arg_error $tmp_main_arg
			fi
			main_arg+=("$tmp_main_arg")
		fi
	done 
	filter_arg
	
	echo ${main_arg[@]}
	
	find_package
	for package_not_found in ${not_found_package[@]};do
		echo "package $package_not_found not found"
	done
	
	for arg in ${package[@]};do
		PACKAGE_FULL_PATH="${arg}"
		PACKAGE_NAME=$(basename $PACKAGE_FULL_PATH)
		for name in $(echo "$PACKAGE_FULL_PATH" | tr "\n" " ");do 
			echo "found package: $(basename $name)"
		done
		BINS=""
		BIN=$(cat $PACKAGE_FULL_PATH | grep "bin")
		BINS=$(string_winding $BIN)

		
		for st in $(echo "$BINS" | tr "\n" " ");do
			echo "binary: $(basename $st)"
		
			TMP=$(ldd_check $st)
			TMP=$(filter_arg_str $TMP)
			for st1 in $TMP;do
				TMPI="$(file_search $st1)"
				if [[ "$TMPI" ]];then
					if [[ "$PACKAGE_ONLY" == "1" ]];then
						echo "$TMPI"
					else
						echo -e "\t$st1 --> $(echo "$TMPI" | sed ':a;N;$!ba;s/\n/ and /g')"
					fi
				else
					echo -e "\t$st1 is not packages"
				fi
			done
		done
	done
	if [ "$NO_TIME" == "0" ];then
		echo "Time: $(counting_time)"
	fi
}



main $@
