#!/usr/bin/bash

#info
VERSION=1.0

#env and path
[ -z "$ROOT" ] && ROOT="/"
PATH=$ROOT/bin:$ROOT/usr/bin:$ROOT/usr/sbin:$ROOT/usr/local/bin:$ROOT/usr/local/sbin
PATH_PACKAGE=$ROOT/var/log/packages
SLACKWARE_VERSION=$(cat $ROOT/etc/slackware-version)
[ -z "$LDD" ] && LDD=$ROOT/usr/bin/ldd
WORKDIR=$ROOT/var/lib/slackpkg
PREPO=slackware	

#time
NO_TIME=0
SECONDS=0

#repo
PRIORITY=($(ls $WORKDIR/*-filelist.gz | xargs -n1 basename | sed 's/-filelist\.gz$//'))
declare -A CACHED_LISTS
FILE_NAME=""

#tmp
if [ -z "$RAM_CACHE" ]; then
    if [ -d /dev/shm ] && [ -w /dev/shm ]; then
        RAM_CACHE=/dev/shm/slackldd_cache_$$
    else
        RAM_CACHE=/tmp/slackldd_cache_$$
    fi
fi


#exit
trap "rm -rf $RAM_CACHE" EXIT


help(){
	if [[ "$1" == "h" ]];then
		echo "slackldd [-v] [-t] [-s] [-o filename] package"
	elif [[ "$1" == "arg_error" ]];then
		echo "invalid argument: $2"
	elif [[ "$1" == "v" ]];then
		echo "slackldd version: $VERSION"
	else
		echo "error"
	fi
	exit
}




counting_time() {
    local m h d s
    local result=""

    d=$(( SECONDS / 86400 ))
    h=$(( (SECONDS / 3600) % 24 ))
    m=$(( (SECONDS / 60) % 60 ))
    s=$(( SECONDS % 60 ))
    (( d > 0 )) && result+="day: $d "
    (( h > 0 )) && result+="hour: $h "
    (( m > 0 )) && result+="min: $m "
    result+="sec: $s"

    echo "$result"
}

cutpkg(){
    echo "$1" | sed -E 's/-[0-9].*//'
}



preload_cache() {
	mkdir -p "$RAM_CACHE"
    for repo in "${PRIORITY[@]}"; do
        local FILELIST="${WORKDIR}/${repo}-filelist.gz"
        if [[ -f "$FILELIST" ]]; then
            zcat "$FILELIST" > "$RAM_CACHE/$repo"
        fi
    done
}


file_search(){
    local INPUTLIST="$1"
    local PKGNAMELIST=$(mktemp)
    local RESULT_LIST=""


    for i in "${PRIORITY[@]}"; do
        FILELIST="${WORKDIR}/${i}-filelist.gz"
        if [ -f "$FILELIST" ]; then
	    PKGS=$(cat "$RAM_CACHE/$i" | grep "$INPUTLIST" | awk '{print $1}' | xargs -r -n1 basename)
            for FULLNAME in $PKGS ; do
                NAME=$(cutpkg "$FULLNAME")
                if ! grep -q "^${NAME}$" "$PKGNAMELIST"; then
					echo "$NAME" >> "$PKGNAMELIST"
					if [[ "$PACKAGE_ONLY" == "1" ]] || [[ "$SORT_PACKAGES" == "1" ]];then
						echo -e "${FULLNAME%.*}"
                    else
						echo -e "${FULLNAME%.*} in $i"
						PACKAGES_SORTS+=("${FULLNAME%.*}")
                    fi
                fi
            done
        fi
    done

    rm -f "$PKGNAMELIST"
}



ldd_check(){
	for st in "$@";do
		$LDD "$ROOT/$st" 2>/dev/null | awk '/not found/ {print $1}'
	done
}

check_exe() {
	if [[ -x "$ROOT/$1" ]] && [[ -f "$ROOT/$1" ]]; then
		return 0
	fi
	return 1
}
string_winding(){
	for st in "$@";do
		if check_exe "$st";then
			echo "$BINS $st"
		fi
	done
}
     


find_package() {
    package=()
    not_found_package=()
    local PENDING=("${main_arg[@]}")

    for i in "${PRIORITY[@]}"; do
        [[ ${#PENDING[@]} -eq 0 ]] && break
        local FILELIST="${WORKDIR}/${i}-filelist.gz"
        [[ ! -f "$FILELIST" ]] && continue

        local NEXT_PENDING=()
        for st in "${PENDING[@]}"; do
			if grep -qFm1 "$st" "$RAM_CACHE/$i"; then
                local ACTUAL_LOG=( "$PATH_PACKAGE/$st"-* )
                if [[ -f "${ACTUAL_LOG[0]}" ]]; then
                    package+=("${ACTUAL_LOG[0]}") 
                else
                    package+=("$st") 
                fi
            else
                NEXT_PENDING+=("$st")
            fi
        done
        PENDING=("${NEXT_PENDING[@]}")
    done
    not_found_package=("${PENDING[@]}")
}

filter_arg(){
    local -A seen
    for i in "${!main_arg[@]}"; do
        local val="${main_arg[$i]}"
        if [[ -n "${seen[$val]}" ]]; then
            unset "main_arg[$i]" 
        else
            seen[$val]=1
        fi
    done
    main_arg=("${main_arg[@]}") 
}



not_found_package=()
package=()
main_arg=()
PACKAGES_SORTS=()
EFI_NOT_FOUND=()
main(){
	shopt -s nullglob
	preload_cache
	BINS=""
	BIN=""
	if [[ "$@" == "" ]];then
		help h
	fi
	
	for tmp_main_arg in "$@";do
		if [[ "$tmp_main_arg" == "-h" ]];then
			help h
		elif [[ "$tmp_main_arg" == "-v" ]];then
			help v
		elif [[ "$tmp_main_arg" == "-f" ]];then
			FILE=1
			continue
		elif [[ "$tmp_main_arg" == "-t" ]];then
			NO_TIME=1
		elif [[ "$tmp_main_arg" == "-s" ]];then
			SORT_PACKAGES=1
		elif [[ "$tmp_main_arg" == "-p" ]];then
			PACKAGE_ONLY=1
			continue
		else
			if [[ "${tmp_main_arg::1}" == "-" ]];then
				help arg_error $tmp_main_arg
			fi
			main_arg+=("$tmp_main_arg")
		fi
		
		if [[ "$FILE" == "1" ]];then
			FILE_NAME="$tmp_main_arg"
			FILE=0
			continue
		elif [[ -v FILE_NAME ]];then
			continue
		else
			help h
		fi
		
	done
	
	filter_arg
	
	
	find_package
	[[ "$PACKAGE_ONLY" != "1" ]] && for package_not_found in ${not_found_package[@]};do
		echo "package $package_not_found not found"
	done
	
	for arg in "${package[@]}";do
		if [[ -f "$arg" ]]; then
			PACKAGE_FULL_PATH="${arg}"
			PACKAGE_NAME=$(basename $PACKAGE_FULL_PATH)
			[[ "$PACKAGE_ONLY" != "1" ]] && for name in $(echo "$PACKAGE_FULL_PATH");do 
				echo "found package: $(basename $name)"
			done
			BINS=""
			BINS=$(string_winding $(cat "$arg"))

		
			for st in $BINS;do
				if [[ "$PACKAGE_ONLY" != "1" ]] ; then echo "binary: $(basename "$st")";fi
		
				TMP=$(ldd_check $st)
				for st1 in $TMP;do
					TMPI="$(file_search $st1)"
					if [[ "$TMPI" ]];then
						if [[ "$PACKAGE_ONLY" == "1" ]];then
							echo "$TMPI"
							[[ -v FILE_NAME ]] && PACKAGES_SORTS+=("$TMPI")
						elif [[ "$SORT_PACKAGES" == "1" ]];then
							PACKAGES_SORTS+=("$TMPI")
							printf "."
						else
							echo -e "\t$st1 --> $(echo "$TMPI" | paste -sd ' ' - | sed 's/ / and /g')"
							[[ -v FILE_NAME ]] && PACKAGES_SORTS+=("$TMPI")
						fi
					else
						if  [[ "$SORT_PACKAGES" == "1" ]] || [[ "$PACKAGE_ONLY" == "1" ]];then EFI_NOT_FOUND+=("$st1");
						else  echo -e "\t$st1 is not packages";fi
					fi
				done
			done
		fi
	done
	
	if [[ -v FILE_NAME ]];then
		printf "%s\n" "${PACKAGES_SORTS[@]}" | sort -u >> "$FILE_NAME"
	else
		[[ "$SORT_PACKAGES" == "1" ]] && printf "packages: " && printf "%s\n" "${PACKAGES_SORTS[@]}" | sort -u | xargs &&\
		 printf "efi lib o bin not found: " && printf "%s\n" "${EFI_NOT_FOUND[@]}" | sort -u | xargs
	fi
	[[ "$NO_TIME" == "0" ]] && echo "Time: $(counting_time)"

}



main $@
